name: Build and Push Docker Image (Dev)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Apply (Dev)"]
    types: [completed]


permissions:
  id-token: write
  contents: read
  actions: read     # to download artifacts from another workflow

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./docker/Dockerfile

      # ✅ Download Terraform output artifact
      - name: Download ECR URL artifact
        uses: actions/download-artifact@v4
        with:
          name: ecr-url-Dev   # matches Terraform upload
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{github.token }}
          repository: ${{ github.repository }}
          path: infra/terraform/envs/dev




      
      - name: Verify artifact
        run: |
          echo "Files in infra/terraform/envs/dev:"
          ls -l infra/terraform/envs/dev



      - name: Read ECR URL
        run: |
          ECR_URL=$(cat infra/terraform/envs/dev/ecr_repo_url.txt)
          echo "REPO_URL=$ECR_URL" >> $GITHUB_ENV
          echo "Using $ECR_URL"



      # ✅ Configure AWS credentials for Docker
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557690622944:role/github-actions-role
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      # ✅ Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      # ✅ Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image $REPO_URL:dev-latest"
          docker build -t "${REPO_URL}:dev-latest" -f docker/Dockerfile .

      # ✅ Push Docker image
      - name: Push Docker image to ECR
        run: |
          docker push "${REPO_URL}:dev-latest"


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false


      - name: Terraform Init
        working-directory: infra/terraform/envs/dev
        run: terraform init


      - name: Update ECS Task Definition
        working-directory: infra/terraform/envs/dev
        run: |
          REPO_URL=$(cat ecr_repo_url.txt)
          terraform apply -auto-approve \
            -var="container_image=${REPO_URL}:dev-latest"
