name: Build and Push Docker Image (Prod)

on:
  push:
    branches: [main]
  workflow_dispatch:




permissions:
  id-token: write
  contents: read


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./docker/Dockerfile

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557690622944:role/github-actions-role
          aws-region: ${{ secrets.DEV_AWS_REGION }}


      # Get the dynamically created repository URL from Terraform
      - name: Get ECR repository URL
        id: ecr
        run: |
          echo "REPO_URL=$(terraform -chdir=infa/terraform/envs/prod output -raw repository_url)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ secrets.DEV_AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build \
            -t $REPO_URL:prod-latest \
            -f docker/Dockerfile \
            .

      - name: Push Docker image to ECR
        run: |
          docker push $REPO_URL:prod-latest