name: Build and Push Docker Image (Dev)

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.10.0
        with:
          dockerfile: ./docker/Dockerfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker build \
            -t ${{ secrets.ECR_REPO_NAME }}:dev-$SHORT_SHA \
            -t ${{ secrets.ECR_REPO_NAME }}:dev-latest ./docker


      - name: Tag image for ECR
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker tag ${{ secrets.ECR_REPO_NAME }}:dev-$SHORT_SHA \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.DEV_AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:dev-$SHORT_SHA
          docker tag ${{ secrets.ECR_REPO_NAME }}:dev-latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.DEV_AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:dev-latest

#      - name: Push image to ECR
#        run: |
#          SHORT_SHA=${GITHUB_SHA::7}
#          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.DEV_AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:dev-$SHORT_SHA
#          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.DEV_AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:dev-latest
