name: Terraform Apply (Dev)

on:
  push:
    branches: [main1]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # --- OIDC login ---
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::557690622944:role/github-actions-role
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          terraform -chdir=infa/terraform/envs/dev init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=dev/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform -chdir=infa/terraform/envs/dev validate 

      - name: Terraform Plan
        run: terraform -chdir=infa/terraform/envs/dev plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=infa/terraform/envs/dev apply -auto-approve tfplan

      - name: Wait 2 minutes
        run: sleep 120   # 120 seconds = 2 minutes

      - name: Terraform Destroy
        run: terraform destroy -auto-approve